// Code generated by meta. DO NOT EDIT.

package testdata

import (
	"context"
)

//+some.Some one="1"
//+any.Any two="2"
/*+more.More three="3"
four="4"
*/
type CommentsIfaceStructIface interface {
}

type CustomIface interface {
}

type NoneMethodStructIface interface {
}

type SomeStructIface interface {
	PublicMethod(ctx context.Context, id int64) (string, error)
}
