// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gomelon/metas/mwire/testdata/bar"
)

// Injectors from wire.go:

func initApp(greeting bar.Greeting, bye bar.Bye) (*App, error) {
	defaultFoo := bar.NewDefaultFoo()
	fooAOPWithGreetImpl := bar.NewFooAOPWithGreet(defaultFoo, greeting)
	fooAOPWithByeImpl := bar.NewFooAOPWithBye(fooAOPWithGreetImpl, bye)
	app := NewApp(fooAOPWithByeImpl)
	return app, nil
}
